name: Document

on:
  push:
    paths:
    - 'hillside46/*-doc.kibot.yaml'
    - '.github/workflows/document.yaml'
  workflow_dispatch:

env:
  BOARD: hillside46

jobs:
  export:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./${{ env.BOARD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: KiBot
        uses: INTI-CMNB/KiBot@v2_dk6
        with:
          config: ./${{ env.BOARD }}/${{ env.BOARD }}-doc.kibot.yaml
          schema: ./${{ env.BOARD }}/${{ env.BOARD }}.kicad_sch
          board: ./${{ env.BOARD }}/${{ env.BOARD }}.kicad_pcb
          dir: ./${{ env.BOARD }}
          skip: run_drc
          verbose: 3
          
      - name: Upload Docs Zip
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: ./${{ env.BOARD }}/${{ env.BOARD }}-Doc.zip

      - name: Debug list directory
        run: |
          pwd
          ls -la
          ls -la docs
