name: Document

on:
  push:
    paths:
    - 'hillsideview46/bin/doc.kibot.yaml'
    - '.github/workflows/document.yaml'
  workflow_dispatch:

env:
  BOARD: hillsideview46

jobs:
  export:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./${{ env.BOARD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create doc_out folder with write access
        run: |
          mkdir doc_out
          ls -la 

      - name: KiBot
        uses: INTI-CMNB/KiBot@v2_k6_1_6_0
        with:
          config: ./${{ env.BOARD }}/bin/doc.kibot.yaml
          schema: ./${{ env.BOARD }}/${{ env.BOARD }}.kicad_sch
          board: ./${{ env.BOARD }}/${{ env.BOARD }}.kicad_pcb
          dir: ./${{ env.BOARD }}
          verbose: 3

      - name: Resize render, zip
        run: |
          convert doc_out/hillsideview46-3D_top.png -resize 1200 doc_out/hillsideview46-3D_1200.png
          ls -la . doc_out
          cd doc_out
          zip ../${{ env.BOARD }}-Doc.zip *.html *.png *.svg
          
      - name: Upload Docs Zip
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: ./${{ env.BOARD }}/${{ env.BOARD }}-Doc.zip

      ####
      # Logs
      - name: Debug list directory
        if: ${{ always() }}
        run: |
          pwd
          ls -la . doc_out

      - name: Upload Logs
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: docs_debug_logs
          path: |
            ./${{ env.BOARD }}/*.log
            ./${{ env.BOARD }}/*.txt
            ./${{ env.BOARD }}/doc_out/*.log
            ./${{ env.BOARD }}/doc_out/*.txt
