name: Document

on:
  push:
    paths:
    - 'hillside46/bin/doc.kibot.yaml'
    - '.github/workflows/document.yaml'
  workflow_dispatch:

env:
  BOARD: hillside46

jobs:
  export:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./${{ env.BOARD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: KiBot
        uses: INTI-CMNB/KiBot@v2_dk6
        with:
          config: ./${{ env.BOARD }}/bin/doc.kibot.yaml
          schema: ./${{ env.BOARD }}/${{ env.BOARD }}.kicad_sch
          board: ./${{ env.BOARD }}/${{ env.BOARD }}.kicad_pcb
          dir: ./${{ env.BOARD }}
          verbose: 3
          
      - name: Upload Docs Zip
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: ./${{ env.BOARD }}/${{ env.BOARD }}-Doc.zip

      ####
      # Logs
      - name: Debug list directory
        if: ${{ always() }}
        run: |
          pwd
          ls -la
          ls -la doc_out

      - name: Upload Logs
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: doc_debug_logs
          path: |
            ./${{ env.BOARD }}/*.log
            ./${{ env.BOARD }}/*.txt
            ./${{ env.BOARD }}/doc_out/*.log
            ./${{ env.BOARD }}/doc_out/*.txt
