name: Fabricate

on:
  push:
    paths:
    - 'hillside46/*.kicad_sch'
    - 'hillside46/*.kicad_pcb'
    - 'hillside46/bin/fab.kibot.yaml'
    - 'hillside46/bin/pos_back.py'
    - '.github/workflows/fabricate.yaml'
  workflow_dispatch:

env:
  BOARD: hillside46

jobs:
  generate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./${{ env.BOARD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create position and PCBA folders with write access
        run: |
          mkdir position
          mkdir pcba
          ls -la 

      - name: KiBot
        uses: INTI-CMNB/KiBot@v2_dk6
        with:
          config: ./${{ env.BOARD }}/bin/fab.kibot.yaml
          schema: ./${{ env.BOARD }}/${{ env.BOARD }}.kicad_sch
          board: ./${{ env.BOARD }}/${{ env.BOARD }}.kicad_pcb
          dir: ./${{ env.BOARD }}
          verbose: 1

      - name: Create position file for back of boards
        run: |
          ./bin/pos_back.py \
            < position/boards_12_top_cpl.csv \
            > position/boards_34_bottom_cpl.csv

      - name: Zip position files with readme
        run: |
          zip --junk-paths pcba/position_files.zip \
             position/*.csv  doc/README_pcba.md
          ls -la . pcba

      - name: Upload Gerber zip, BOM, position zip
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.BOARD }}-gerber-and-pcba
          path: |
            ./${{ env.BOARD }}/${{ env.BOARD }}-gerbers.zip
            ./${{ env.BOARD }}/pcba/*
            
      ####
      # Logs
      - name: Debug list directory
        if: ${{ always() }}
        run: |
          pwd
          ls -la . gerber pcba position
        
      - name: Upload Logs
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.BOARD }}-debug_logs_fab
          path: |
            ./${{ env.BOARD }}/*.log
            ./${{ env.BOARD }}/*.txt

