name: Fabricate

on:
  push:
    paths:
    - 'hillside46/*.kicad_sch'
    - 'hillside46/*.kicad_pcb'
    - 'hillside46/bin/fab.kibot.yaml'
    - 'hillside46/bin/pos_back.py'
    - '.github/workflows/fabricate.yaml'
  workflow_dispatch:

env:
  BOARD: hillside46

jobs:
  generate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./${{ env.BOARD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: KiBot
        uses: INTI-CMNB/KiBot@v2_dk6
        with:
          config: ./${{ env.BOARD }}/bin/fab.kibot.yaml
          schema: ./${{ env.BOARD }}/${{ env.BOARD }}.kicad_sch
          board: ./${{ env.BOARD }}/${{ env.BOARD }}.kicad_pcb
          dir: ./${{ env.BOARD }}
          verbose: 1

      - name: PosBottom
        run: |
          ./bin/pos_back.py \
            < pcba/boards_12_top_cpl.csv \
            > boards_34_bottom_cpl.csv
            
      - name: Upload Gerber
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.BOARD }}-gerbers
          path: ./${{ env.BOARD }}/${{ env.BOARD }}-Gerbers.zip

      - name: Upload BOM
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.BOARD }}-bom
          path: ./${{ env.BOARD }}/pcba/${{ env.BOARD }}_bom.csv

      - name: Collect position files
        run: |
          cp pcba/boards_12_top_cpl.csv .
          cp doc/README_pcba.md .
          ls -la

      - name: Upload Position files
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.BOARD }}-position
          path: |
             ./${{ env.BOARD }}/boards_12_top_cpl.csv
             ./${{ env.BOARD }}/boards_34_bottom_cpl.csv
             ./${{ env.BOARD }}/README_pcba.md

      ####
      # Logs
      - name: Debug list directory
        if: ${{ always() }}
        run: |
          pwd
          ls -la
          ls -la gerber
          ls -la pcba
          cat pcba/boards_12_top_cpl.csv
          cat boards_34_bottom_cpl.csv
        
      - name: Upload Logs
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.BOARD }}-debug_logs_fab
          path: |
            ./${{ env.BOARD }}/*.log
            ./${{ env.BOARD }}/*.txt

