name: Fabricate

on:
  push:
    paths:
    - 'hillside46/*.kicad_sch'
    - 'hillside46/*.kicad_pcb'
    - 'hillside46/*-fab.kibot.yaml'
    - '.github/workflows/fabricate.yaml'
  workflow_dispatch:

env:
  BOARD: hillside46


jobs:
  generate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./${{ env.BOARD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: KiBot
        uses: INTI-CMNB/KiBot@v2_dk6
        continue-on-error: true

        with:
          config: ./${{ env.BOARD }}/${{ env.BOARD }}-fab.kibot.yaml
          schema: ./${{ env.BOARD }}/${{ env.BOARD }}.kicad_sch
          board: ./${{ env.BOARD }}/${{ env.BOARD }}.kicad_pcb
          dir: ./${{ env.BOARD }}
          verbose: 3

      - name: Upload Gerber Zip
        uses: actions/upload-artifact@v3
        with:
          name: gerbers
          path: ./${{ env.BOARD }}/${{ env.BOARD }}-Fab.zip

      - name: Upload PCBA Zip
        uses: actions/upload-artifact@v3
        with:
          name: pcba
          path: ./${{ env.BOARD }}/${{ env.BOARD }}-PCBA.zip

    
      - name: Debug list directory
        if: ${{ always() }}
        run: |
          pwd
          ls -la
          ls -la gerber
        
      - name: Upload Logs
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: logs
          path: |
            ./${{ env.BOARD }}/*.log
            ./${{ env.BOARD }}/*.txt

