name: Fabricate

on:
  push:
    paths:
    - 'hillside46/*.kicad_sch'
    - 'hillside46/*.kicad_pcb'
    - 'hillside46/bin/fab.kibot.yaml'
    - '.github/workflows/fabricate.yaml'
  workflow_dispatch:

env:
  BOARD: hillside46

jobs:
  generate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./${{ env.BOARD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: KiBot
        uses: INTI-CMNB/KiBot@v2_dk6
        with:
          config: ./${{ env.BOARD }}/bin/fab.kibot.yaml
          schema: ./${{ env.BOARD }}/${{ env.BOARD }}.kicad_sch
          board: ./${{ env.BOARD }}/${{ env.BOARD }}.kicad_pcb
          dir: ./${{ env.BOARD }}
          verbose: 1

      - name: PosBottom
        run: |
          ./bin/pos_back.py \
            < pcba/${{ env.BOARD }}_cpl_top.csv \
            > ${{ env.BOARD }}_cpl_bottom.csv
            
      - name: Upload Gerber
        uses: actions/upload-artifact@v3
        with:
          name: gerbers
          path: ./${{ env.BOARD }}/${{ env.BOARD }}-Gerbers.zip

      - name: Upload BOM
        uses: actions/upload-artifact@v3
        with:
          name: bom
          path: ./${{ env.BOARD }}/pcba/${{ env.BOARD }}_bom.csv

      - name: Upload Position
        uses: actions/upload-artifact@v3
        with:
          name: position
          path: |
             ./${{ env.BOARD }}/pcba/${{ env.BOARD }}_cpl_top.csv
             ./${{ env.BOARD }}_cpl_bottom.csv
             ./doc/README_pcba.md

      ####
      # Logs
      - name: Debug list directory
        if: ${{ always() }}
        run: |
          pwd
          ls -la
          ls -la gerber
          ls -la pcba
        
      - name: Upload Logs
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: debug_logs_fab
          path: |
            ./${{ env.BOARD }}/*.log
            ./${{ env.BOARD }}/*.txt

